name: Dependabot Fixer
permissions:
  contents: write
  pull-requests: read

on:
  pull_request:
    branches: [main]

jobs:
  fix-lockfile:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Update Lockfile
        run: |
          bun install

      - name: Commit and Push
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --global user.name 'dependabot-fixer[bot]'
            git config --global user.email 'dependabot-fixer[bot]@users.noreply.github.com'
            git add bun.lock
            git commit -m "fix(deps): update bun.lock to match package.json" --no-verify
            git push
          fi
